(()=>{'use strict';
const API='https://darkstat.dd84ai.com/api/pobs';
const HEALTH_MAX=24000000,REFRESH_MS=300000,TIMEOUT_MS=18000;
const KEYS={live:'dtr:pobs:live:v2',previous:'dtr:pobs:previous:v2',watch:'dtr:watchlist:v1',view:'dtr:view:v1'};
const POBS=[
{key:'deterrence-sanctum',short:'SANCTUM',label:'Deterrence Sanctum',aliases:['deterrence sanctum']},
{key:'ravenna-invicta',short:'INVICTA',label:'Ravenna Invicta',aliases:['ravenna invicta','invicta']},
{key:'forja-del-vacio',short:'FORJA',label:'Forja del Vacio',aliases:['forja del vacio','forja del vacío']},
{key:'fort-torrelavega',short:'TORRELAVEGA',label:'Fort Torrelavega',aliases:['fort torrelavega','torrelavega']}
];
const MAINT=[
{key:'basic alloy',label:'Basic Alloy',code:'ALLOY',critical:2500,warn:15000},
{key:'food rations',label:'Food Rations',code:'FOOD',critical:2500,warn:15000},
{key:'consumer goods',label:'Consumer Goods',code:'GOODS',critical:2500,warn:15000}
];
const $=id=>document.getElementById(id),E={uplink:$('uplink'),status:$('statusText'),refresh:$('refreshButton'),tabs:$('tabs'),overview:$('overviewView'),detail:$('detailView'),grid:$('overviewGrid'),overviewSync:$('overviewSync'),networkState:$('networkState'),metricNodes:$('metricNodes'),metricNodesSub:$('metricNodesSub'),metricCredits:$('metricCredits'),metricCreditsDelta:$('metricCreditsDelta'),metricStorage:$('metricStorage'),metricStorageDelta:$('metricStorageDelta'),metricAlerts:$('metricAlerts'),metricAlertsSub:$('metricAlertsSub'),matrix:$('networkMatrix'),kicker:$('detailKicker'),name:$('detailName'),location:$('detailLocation'),badge:$('detailHealthBadge'),detailDelta:$('detailDelta'),health:$('healthValue'),meter:$('healthMeter'),healthDelta:$('healthDelta'),credits:$('creditsValue'),creditsDelta:$('creditsDelta'),storage:$('storageValue'),storageDelta:$('storageDelta'),sync:$('syncValue'),syncMode:$('syncMode'),maintenance:$('maintenanceGrid'),facilityState:$('facilityState'),priority:$('priorityList'),priorityCount:$('priorityCount'),watchGrid:$('watchGrid'),watchCount:$('watchCount'),search:$('inventorySearch'),filters:$('inventoryFilters'),body:$('inventoryBody'),empty:$('inventoryEmpty'),error:$('errorView'),errorText:$('errorText'),footer:$('footerState'),freshness:$('headerFreshness'),clock:$('headerClock'),offline:$('offlineBanner'),systemButton:$('systemButton'),systemPanel:$('systemPanel'),systemClose:$('systemClose'),systemGrid:$('systemGrid'),systemOverall:$('systemOverall'),systemRefresh:$('systemRefresh'),systemInstall:$('systemInstall'),installButton:$('installButton'),installSheet:$('installSheet'),installTitle:$('installTitle'),installMessage:$('installMessage'),installPrimary:$('installPrimary'),installClose:$('installClose')};
let data=[],previousData=[],bases=new Map(),previousBases=new Map(),view=localStorage.getItem(KEYS.view)||'overview',last=null,mode='none',timer=null,inventoryFilter='all',installPrompt=null,registration=null;
const num=new Intl.NumberFormat('de-DE'),fmt=n=>Number.isFinite(n)?num.format(Math.round(n)):'—',cash=n=>Number.isFinite(n)?`${num.format(Math.round(n))} cr`:'—';
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim(),finite=v=>{const x=Number(v);return Number.isFinite(x)?x:null},esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function loadJson(k){try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}}function saveJson(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}}
function findBase(def,source=data){const aliases=def.aliases.map(norm);return source.find(b=>{const hay=norm([b?.name,b?.nickname,b?.base_name,b?.display_name].filter(Boolean).join(' '));return aliases.some(a=>hay===a||hay.includes(a))})||null}
function rebuild(){bases=new Map(POBS.map(p=>[p.key,findBase(p,data)]));previousBases=new Map(POBS.map(p=>[p.key,findBase(p,previousData)]))}
function hpRaw(b){return finite(b?.health??b?.base_health??b?.hitpoints)}function hp(b){const raw=hpRaw(b);if(raw===null)return null;return Math.max(0,Math.min(100,raw<=100?raw:raw/HEALTH_MAX*100))}function hpText(b){const x=hp(b);return x===null?'—':`${x>=99.95?x.toFixed(0):x.toFixed(1)}%`}function hpTone(b){const x=hp(b);return x===null?'muted':x<35?'danger':x<75?'warn':'good'}function creditsRaw(b){return finite(b?.money??b?.credits??b?.base_money)}function storageRaw(b){return finite(b?.cargospace??b?.cargo_space??b?.cargo_space_left??b?.storage_free)}
function loc(b){if(!b)return'POB NOT FOUND IN CURRENT FEED';const pos=b?.pos??b?.base_pos??b?.position;let p='';if(typeof pos==='string')p=pos;else if(pos&&typeof pos==='object'){const vals=[finite(pos.x??pos.X),finite(pos.y??pos.Y),finite(pos.z??pos.Z)].filter(v=>v!==null);if(vals.length)p=vals.map(Math.round).join(' / ')}return[b?.region_name??b?.region,b?.system_name??b?.system,b?.sector_coord??b?.sector,p].map(v=>String(v??'').trim()).filter(Boolean).join(' // ')||'LOCATION DATA UNAVAILABLE'}
function items(b){const x=b?.shop_items??b?.shopItems??b?.goods??[];return Array.isArray(x)?x:[]}function itemName(i){return String(i?.name??i?.good_name??i?.commodity_name??i?.nickname??i?.good??'UNKNOWN ITEM')}function itemKey(i){return norm(itemName(i))}function qty(i){return finite(i?.quantity??i?.amount??i?.stock)??0}function buy(i){return finite(i?.price_to_sell_to_base??i?.sell_price??i?.price_sell)}function sell(i){return finite(i?.price_to_buy_from_base??i?.buy_price??i?.price_buy)}function price(v){return v===null?'—':`${num.format(Math.round(v))} cr`}function itemByName(b,name){const key=norm(name);return items(b).find(i=>itemKey(i)===key)||null}
function syncText(){if(!last)return'NO DATA';return`${mode==='cache'?'CACHE':'LIVE'} // ${last.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}`}function status(state,text){E.uplink.dataset.state=state;E.status.textContent=text;E.footer.textContent=text;E.freshness.textContent=last?syncText():text}
function delta(c,p){return Number.isFinite(c)&&Number.isFinite(p)?c-p:null}function deltaMarkup(v,unit='',inverse=false){if(v===null||Math.abs(v)<.0001)return'<span data-tone="muted">NO CHANGE</span>';const positive=v>0,good=inverse?!positive:positive,sign=positive?'+':'−',abs=Math.abs(v),text=unit==='%'?abs.toFixed(1):num.format(Math.round(abs));return`<span data-tone="${good?'good':'danger'}">${sign}${text}${unit}</span>`}function setDelta(el,v,unit='',inverse=false){el.innerHTML=deltaMarkup(v,unit,inverse)}
function maintenanceState(item,def){if(!item)return'danger';const q=qty(item);return q<def.critical?'danger':q<def.warn?'warn':'good'}function maintenanceStatus(item,def){const state=maintenanceState(item,def),q=item?qty(item):0;if(state==='danger')return q<=0?'DEPLETED':'CRITICAL RESERVE';if(state==='warn')return'LOW RESERVE';return'OPERATIONAL'}function baseMaintenance(b){return MAINT.map(def=>({def,item:itemByName(b,def.label),state:maintenanceState(itemByName(b,def.label),def)}))}function severity(s){return s==='danger'?2:s==='warn'?1:0}function worst(states){return states.reduce((a,b)=>severity(b)>severity(a)?b:a,'good')}
function baseAlerts(def,b){const alerts=[];if(!b){alerts.push({tone:'danger',title:'NODE OFFLINE',detail:`${def.label} not found in current telemetry.`});return alerts}const h=hp(b);if(h!==null&&h<75)alerts.push({tone:h<35?'danger':'warn',title:'STRUCTURAL INTEGRITY',detail:`Facility health at ${hpText(b)}.`});baseMaintenance(b).forEach(({def,item,state})=>{if(state!=='good')alerts.push({tone:state,title:`${def.label.toUpperCase()} ${state==='danger'?'CRITICAL':'LOW'}`,detail:`${fmt(item?qty(item):0)} units in maintenance reserve.`})});return alerts}
function watchlist(){const raw=loadJson(KEYS.watch);return Array.isArray(raw)?raw.filter(x=>x&&x.key&&x.label):[]}function setWatchlist(list){saveJson(KEYS.watch,list)}function isWatched(name){const k=norm(name);return watchlist().some(x=>x.key===k)}function toggleWatch(name){const key=norm(name),list=watchlist(),index=list.findIndex(x=>x.key===key);if(index>=0)list.splice(index,1);else list.push({key,label:String(name)});setWatchlist(list);render()}
function totalMetric(getter,map=bases){let total=0,count=0;POBS.forEach(p=>{const b=map.get(p.key),v=b?getter(b):null;if(Number.isFinite(v)){total+=v;count++}});return count?total:null}function totalAlerts(){return POBS.reduce((sum,p)=>sum+baseAlerts(p,bases.get(p.key)).length,0)}
function renderNetworkMetrics(){const found=POBS.filter(p=>bases.get(p.key)).length,alerts=totalAlerts();E.metricNodes.textContent=`${found}/4`;E.metricNodesSub.textContent=mode==='cache'?'CACHED NODE SNAPSHOT':found===4?'ALL NODES VERIFIED':`${4-found} NODE${4-found===1?'':'S'} MISSING`;const c=totalMetric(creditsRaw),pc=totalMetric(creditsRaw,previousBases),s=totalMetric(storageRaw),ps=totalMetric(storageRaw,previousBases);E.metricCredits.textContent=c===null?'—':cash(c);E.metricCreditsDelta.innerHTML=deltaMarkup(delta(c,pc));E.metricStorage.textContent=s===null?'—':fmt(s);E.metricStorageDelta.innerHTML=deltaMarkup(delta(s,ps));E.metricAlerts.textContent=String(alerts);E.metricAlertsSub.textContent=alerts?'ATTENTION REQUIRED':'NO ACTIVE ALERTS';const tone=found<4?'danger':alerts?'warn':'good';E.networkState.dataset.tone=tone;E.networkState.querySelector('strong').textContent=found<4?'NETWORK DEGRADED':alerts?'NODES ONLINE // ALERTS ACTIVE':'ALL NODES NOMINAL';E.networkState.querySelector('small').textContent=mode==='cache'?'CACHED NETWORK STATE':'NETWORK STATE'}
function miniMaintenance(b){if(!b)return'<div class="maintenance-mini"><span data-tone="danger">NO FEED</span></div>';return`<div class="maintenance-mini">${baseMaintenance(b).map(({def,item,state})=>`<span data-tone="${state}" title="${esc(def.label)}">${def.code}<b>${fmt(item?qty(item):0)}</b></span>`).join('')}</div>`}
function renderOverview(){E.overviewSync.textContent=syncText();renderNetworkMetrics();E.grid.innerHTML=POBS.map((p,index)=>{const b=bases.get(p.key),pb=previousBases.get(p.key),alerts=baseAlerts(p,b);if(!b)return`<article class="base-card" data-base-key="${p.key}" data-state="missing" tabindex="0" role="button"><span class="node-id">NODE 0${index+1}</span><div class="base-card-head"><div><h3>${esc(p.label)}</h3><p class="where">POB not found in current feed</p></div><span class="health-pill" data-tone="danger">OFFLINE</span></div>${miniMaintenance(null)}<div class="base-card-footer"><span>NO VERIFIED TELEMETRY</span><b>${alerts.length} ALERT</b></div></article>`;const cd=delta(creditsRaw(b),creditsRaw(pb)),sd=delta(storageRaw(b),storageRaw(pb)),hd=delta(hp(b),hp(pb));return`<article class="base-card" data-base-key="${p.key}" tabindex="0" role="button"><span class="node-id">NODE 0${index+1}</span><div class="base-card-head"><div><h3>${esc(p.label)}</h3><p class="where">${esc(loc(b))}</p></div><span class="health-pill" data-tone="${hpTone(b)}">${hpText(b)}</span></div><div class="base-card-stats"><div><small>CREDITS</small><strong>${cash(creditsRaw(b))}</strong><em>${deltaMarkup(cd)}</em></div><div><small>FREE STORAGE</small><strong>${fmt(storageRaw(b))}</strong><em>${deltaMarkup(sd)}</em></div><div><small>HEALTH Δ</small><strong>${hd===null?'—':deltaMarkup(hd,'%')}</strong></div></div>${miniMaintenance(b)}<div class="base-card-footer"><span>FACILITY MAINTENANCE</span><b data-tone="${alerts.length?'warn':'good'}">${alerts.length?`${alerts.length} ALERT${alerts.length===1?'':'S'}`:'NOMINAL'}</b></div></article>`}).join('');renderMatrix()}
function matrixRows(){const rows=MAINT.map(x=>({key:x.key,label:x.label,maintenance:x}));watchlist().forEach(w=>{if(!rows.some(r=>r.key===w.key))rows.push({key:w.key,label:w.label,maintenance:null})});return rows}
function renderMatrix(){const rows=matrixRows();E.matrix.innerHTML=`<div class="matrix-table"><div class="matrix-row matrix-head"><span>COMMODITY</span>${POBS.map(p=>`<span>${esc(p.short)}</span>`).join('')}</div>${rows.map(row=>`<div class="matrix-row"><strong>${esc(row.label)}${row.maintenance?'<small>MAINT</small>':'<small>WATCH</small>'}</strong>${POBS.map(p=>{const b=bases.get(p.key),item=b?itemByName(b,row.label):null,state=row.maintenance?maintenanceState(item,row.maintenance):(item?'good':'muted');return`<button type="button" data-matrix-base="${p.key}" data-matrix-item="${esc(row.label)}" data-tone="${state}"><b>${item?fmt(qty(item)):'—'}</b><small>${row.maintenance?maintenanceStatus(item,row.maintenance):(item?'STOCK':'UNLISTED')}</small></button>`}).join('')}</div>`).join('')}</div>`}
function renderMaintenance(b){const rows=baseMaintenance(b),state=worst(rows.map(r=>r.state));E.facilityState.dataset.tone=state;E.facilityState.textContent=state==='danger'?'ACTION REQUIRED':state==='warn'?'RESERVE WATCH':'FACILITY NOMINAL';E.maintenance.innerHTML=rows.map(({def,item,state})=>{const q=item?qty(item):0,pct=Math.min(100,Math.max(0,q/def.warn*100)),pi=previousBases.get(view)?itemByName(previousBases.get(view),def.label):null,d=delta(q,pi?qty(pi):null);return`<article class="maintenance-card" data-tone="${state}"><div class="maintenance-title"><div><small>${def.code} // DAILY FACILITY SUPPLY</small><strong>${esc(def.label)}</strong></div><span>${maintenanceStatus(item,def)}</span></div><div class="maintenance-value"><b>${fmt(q)}</b><em>units</em><span>${deltaMarkup(d)}</span></div><div class="maintenance-meter"><i style="width:${pct}%"></i><mark></mark></div><div class="maintenance-thresholds"><span>CRITICAL &lt; ${fmt(def.critical)}</span><span>LOW &lt; ${fmt(def.warn)}</span></div></article>`}).join('')}
function renderPriority(def,b){const list=baseAlerts(def,b);E.priorityCount.textContent=`${list.length} ALERT${list.length===1?'':'S'}`;E.priorityCount.dataset.tone=list.some(x=>x.tone==='danger')?'danger':list.length?'warn':'good';E.priority.innerHTML=list.length?list.map((a,i)=>`<article data-tone="${a.tone}"><span>0${i+1}</span><div><strong>${esc(a.title)}</strong><p>${esc(a.detail)}</p></div></article>`).join(''):`<div class="priority-empty"><i></i><div><strong>NO ACTIVE ALERTS</strong><span>Facility health and maintenance reserves are nominal.</span></div></div>`}
function renderWatch(b){const list=watchlist();E.watchCount.textContent=`${list.length} WATCHED`;if(!list.length){E.watchGrid.innerHTML='<div class="watch-empty">WATCHLIST EMPTY <small>Star cargo in the manifest to pin it here.</small></div>';return}const pb=previousBases.get(view);E.watchGrid.innerHTML=list.map(w=>{const item=itemByName(b,w.label),pi=pb?itemByName(pb,w.label):null,q=item?qty(item):0,d=delta(q,pi?qty(pi):null);return`<article class="watch-card"><button class="watch-remove" type="button" data-unwatch="${esc(w.label)}" aria-label="Remove ${esc(w.label)} from watchlist">×</button><small>WATCHED CARGO</small><strong>${esc(w.label)}</strong><b>${fmt(q)}</b><span>${deltaMarkup(d)}</span></article>`}).join('')}
function inventoryItemDelta(name,current){const pb=previousBases.get(view),pi=pb?itemByName(pb,name):null;return delta(current,pi?qty(pi):null)}
function renderItems(b){const query=norm(E.search.value),watched=new Set(watchlist().map(x=>x.key));let list=items(b);list=list.filter(i=>{const key=itemKey(i),qmatch=!query||key.includes(query);if(!qmatch)return false;if(inventoryFilter==='watch')return watched.has(key);if(inventoryFilter==='buy')return(buy(i)??0)>0;if(inventoryFilter==='sell')return(sell(i)??0)>0;return true}).sort((a,b)=>itemName(a).localeCompare(itemName(b),'de'));E.body.innerHTML=list.map(i=>{const name=itemName(i),q=qty(i),d=inventoryItemDelta(name,q),star=watched.has(itemKey(i));return`<tr><td data-label="WATCH"><button class="watch-toggle${star?' active':''}" type="button" data-watch="${esc(name)}" aria-label="${star?'Remove':'Add'} ${esc(name)} ${star?'from':'to'} watchlist">★</button></td><td class="item-name" data-label="WARE">${esc(name)}</td><td data-label="MENGE">${fmt(q)}</td><td class="muted" data-label="BASE KAUFT">${esc(price(buy(i)))}</td><td class="muted" data-label="BASE VERKAUFT">${esc(price(sell(i)))}</td><td data-label="Δ STOCK">${deltaMarkup(d)}</td></tr>`}).join('');E.empty.hidden=list.length>0}
function renderDetail(key){const def=POBS.find(p=>p.key===key),b=bases.get(key),pb=previousBases.get(key);E.kicker.textContent=`POB NODE // ${mode==='cache'?'CACHED':'LIVE'}`;E.name.textContent=def?.label??'UNKNOWN POB';E.location.textContent=loc(b);E.sync.textContent=last?last.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit',second:'2-digit'}):'—';E.syncMode.textContent=mode==='cache'?'LAST VERIFIED CACHE':'LIVE DARKSTAT SNAPSHOT';if(!b){E.badge.dataset.tone='danger';E.badge.textContent='OFFLINE';E.health.textContent='—';E.meter.style.width='0';E.credits.textContent='—';E.storage.textContent='—';[E.healthDelta,E.creditsDelta,E.storageDelta].forEach(x=>x.textContent='NO DATA');E.detailDelta.textContent='NODE NOT FOUND IN CURRENT FEED';renderMaintenance(null);renderPriority(def,null);renderWatch(null);renderItems(null);return}const h=hp(b),ht=hpTone(b),hd=delta(h,hp(pb)),cd=delta(creditsRaw(b),creditsRaw(pb)),sd=delta(storageRaw(b),storageRaw(pb));E.badge.dataset.tone=ht;E.badge.textContent=hpText(b);E.health.textContent=hpText(b);E.meter.style.width=`${h??0}%`;E.meter.dataset.tone=ht;E.credits.textContent=cash(creditsRaw(b));E.storage.textContent=fmt(storageRaw(b));setDelta(E.healthDelta,hd,'%',false);setDelta(E.creditsDelta,cd);setDelta(E.storageDelta,sd);const changes=[hd!==null&&Math.abs(hd)>.01,cd!==null&&Math.abs(cd)>=1,sd!==null&&Math.abs(sd)>=1].filter(Boolean).length;E.detailDelta.textContent=pb?`${changes} CORE METRIC CHANGE${changes===1?'':'S'} SINCE PREVIOUS SNAPSHOT`:'NO PREVIOUS SNAPSHOT FOR COMPARISON';renderMaintenance(b);renderPriority(def,b);renderWatch(b);renderItems(b)}
function render(){renderOverview();const detail=view!=='overview';E.overview.hidden=detail;E.detail.hidden=!detail;E.tabs.querySelectorAll('.tab').forEach(btn=>btn.classList.toggle('active',btn.dataset.view===view));if(detail)renderDetail(view);updateSystem()}
function show(next,itemSearch=''){view=POBS.some(p=>p.key===next)?next:'overview';saveJson(KEYS.view,view);E.search.value=itemSearch;inventoryFilter='all';E.filters.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.filter==='all'));render();scrollTo({top:0,behavior:'smooth'})}
function hydrateLatest(){const live=loadJson(KEYS.live),prev=loadJson(KEYS.previous);if(!Array.isArray(live?.data))return false;data=live.data;previousData=Array.isArray(prev?.data)?prev.data:[];last=live.savedAt?new Date(live.savedAt):new Date();mode='cache';rebuild();status('cache','CACHED DATA');render();return true}
function persistLive(nextData){const current=loadJson(KEYS.live);if(Array.isArray(current?.data))saveJson(KEYS.previous,current);saveJson(KEYS.live,{savedAt:new Date().toISOString(),data:nextData});previousData=Array.isArray(current?.data)?current.data:(loadJson(KEYS.previous)?.data||[])}
async function request(){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),TIMEOUT_MS);try{return await fetch(API,{method:'POST',headers:{Accept:'application/json'},signal:controller.signal})}finally{clearTimeout(timeout)}}
async function load(){if(timer)clearTimeout(timer);E.refresh.disabled=true;E.error.hidden=true;status('loading','SYNCING');try{const response=await request();if(!response.ok)throw new Error(`Darkstat HTTP ${response.status}`);const next=await response.json();if(!Array.isArray(next))throw new Error('Invalid POB response');persistLive(next);data=next;last=new Date();mode='live';rebuild();const found=POBS.filter(p=>bases.get(p.key)).length;status('live',`${found}/4 NODES LIVE`);render()}catch(err){if(hydrateLatest()){E.error.hidden=false;E.errorText.textContent='Live uplink failed. Last verified snapshot remains active.'}else{mode='none';status('error','UPLINK FAILED');E.error.hidden=false;E.errorText.textContent=err?.name==='AbortError'?'Darkstat timeout after 18 seconds.':String(err?.message||'Darkstat unavailable.');render()}}finally{E.refresh.disabled=false;timer=setTimeout(load,REFRESH_MS)}}
function storageCheck(){const key=`dtr:probe:${Date.now()}`;try{localStorage.setItem(key,'ok');const ok=localStorage.getItem(key)==='ok';localStorage.removeItem(key);return ok}catch{return false}}function pwaStandalone(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true}
function systemChecks(){const found=POBS.filter(p=>bases.get(p.key)).length,store=storageCheck();return[{label:'NETWORK',tone:navigator.onLine?'good':'warn',status:navigator.onLine?'ONLINE':'OFFLINE',detail:navigator.onLine?'Network access available.':'Cached telemetry only.'},{label:'DARKSTAT',tone:mode==='live'?'good':mode==='cache'?'warn':'danger',status:mode==='live'?'LIVE':mode==='cache'?'CACHE ACTIVE':'NO DATA',detail:last?`Last verified ${last.toLocaleTimeString('de-DE')}.`:'No verified snapshot.'},{label:'POB NODES',tone:found===4?'good':'danger',status:`${found}/4 FOUND`,detail:found===4?'All configured nodes resolved.':`${4-found} node(s) missing from current feed.`},{label:'LOCAL CACHE',tone:store?'good':'danger',status:store?'READY':'UNAVAILABLE',detail:'Last-good data and watchlist storage.'},{label:'APP SHELL',tone:pwaStandalone()||registration?'good':'warn',status:pwaStandalone()?'INSTALLED':registration?'OFFLINE READY':'BROWSER ONLY',detail:pwaStandalone()?'Running standalone.':'PWA shell status.'}]}
function updateSystem(){if(!E.systemGrid)return;const checks=systemChecks(),danger=checks.filter(x=>x.tone==='danger').length,warn=checks.filter(x=>x.tone==='warn').length;E.systemGrid.innerHTML=checks.map(x=>`<article data-tone="${x.tone}"><small>${x.label}</small><strong>${x.status}</strong><span>${x.detail}</span></article>`).join('');E.systemOverall.dataset.tone=danger?'danger':warn?'warn':'good';E.systemOverall.querySelector('strong').textContent=danger?'ATTENTION REQUIRED':warn?'CORE SYSTEMS NOMINAL':'ALL SYSTEMS NOMINAL';E.systemOverall.querySelector('span').textContent=danger?`${danger} blocking check(s).`:warn?`${warn} status notice(s).`:'No active system notices.'}
function openSystem(){updateSystem();E.systemPanel.hidden=false;document.body.classList.add('modal-open');E.systemClose.focus()}function closeSystem(){E.systemPanel.hidden=true;document.body.classList.remove('modal-open');E.systemButton.focus()}
function manualInstall(){const ua=navigator.userAgent;if(/SamsungBrowser/i.test(ua))return{title:'INSTALL DTR IN SAMSUNG INTERNET',message:'Open the Samsung Internet menu (☰), then choose Add page to → Home screen.'};if(/iPhone|iPad|iPod/i.test(ua))return{title:'INSTALL DTR ON IPHONE / IPAD',message:'Open DTR in Safari, tap Share, then choose Add to Home Screen.'};if(/Android/i.test(ua))return{title:'INSTALL DTR ON ANDROID',message:'Open the browser menu (⋮), then choose Install app or Add to Home screen.'};return{title:'INSTALL DTR',message:'Open your browser menu and choose Install app or Add to Home screen.'}}
function showInstall(){if(pwaStandalone())return;const manual=manualInstall();E.installTitle.textContent=installPrompt?'INSTALL DTR COMMAND APP':manual.title;E.installMessage.textContent=installPrompt?'Add DTR to this device for a standalone command window and offline-ready shell.':manual.message;E.installPrimary.textContent=installPrompt?'INSTALL APP':'GOT IT';E.installSheet.hidden=false;document.body.classList.add('modal-open')}
async function doInstall(){if(!installPrompt){E.installSheet.hidden=true;document.body.classList.remove('modal-open');return}try{await installPrompt.prompt();await installPrompt.userChoice}catch{}installPrompt=null;E.installSheet.hidden=true;document.body.classList.remove('modal-open');syncInstallButton()}
function syncInstallButton(){const installed=pwaStandalone();E.installButton.hidden=installed;E.systemInstall.hidden=installed}
async function registerPwa(){if(!('serviceWorker'in navigator))return;try{registration=await navigator.serviceWorker.register('./sw.js',{scope:'./',updateViaCache:'none'});updateSystem()}catch{}}
function updateClock(){E.clock.textContent=new Date().toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}function connectionState(){E.offline.hidden=navigator.onLine;if(!navigator.onLine&&mode==='live'){mode='cache';status('cache','OFFLINE // CACHE')}updateSystem()}
E.tabs.addEventListener('click',e=>{const b=e.target.closest('.tab');if(b)show(b.dataset.view)});E.grid.addEventListener('click',e=>{const c=e.target.closest('[data-base-key]');if(c)show(c.dataset.baseKey)});E.grid.addEventListener('keydown',e=>{if(!['Enter',' '].includes(e.key))return;const c=e.target.closest('[data-base-key]');if(c){e.preventDefault();show(c.dataset.baseKey)}});E.matrix.addEventListener('click',e=>{const b=e.target.closest('[data-matrix-base]');if(b)show(b.dataset.matrixBase,b.dataset.matrixItem)});E.search.addEventListener('input',()=>view!=='overview'&&renderItems(bases.get(view)));E.filters.addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;inventoryFilter=b.dataset.filter;E.filters.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));renderItems(bases.get(view))});E.body.addEventListener('click',e=>{const b=e.target.closest('[data-watch]');if(b)toggleWatch(b.dataset.watch)});E.watchGrid.addEventListener('click',e=>{const b=e.target.closest('[data-unwatch]');if(b)toggleWatch(b.dataset.unwatch)});E.refresh.addEventListener('click',load);E.systemButton.addEventListener('click',openSystem);E.systemClose.addEventListener('click',closeSystem);E.systemRefresh.addEventListener('click',updateSystem);E.systemPanel.addEventListener('click',e=>{if(e.target===E.systemPanel)closeSystem()});E.installButton.addEventListener('click',showInstall);E.systemInstall.addEventListener('click',showInstall);E.installClose.addEventListener('click',()=>{E.installSheet.hidden=true;document.body.classList.remove('modal-open')});E.installPrimary.addEventListener('click',doInstall);addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;syncInstallButton()});addEventListener('appinstalled',()=>{installPrompt=null;E.installSheet.hidden=true;document.body.classList.remove('modal-open');syncInstallButton()});addEventListener('online',()=>{connectionState();load()});addEventListener('offline',connectionState);addEventListener('keydown',e=>{if(e.key==='Escape'){if(!E.systemPanel.hidden)closeSystem();if(!E.installSheet.hidden){E.installSheet.hidden=true;document.body.classList.remove('modal-open')}}});
setInterval(updateClock,1000);updateClock();syncInstallButton();registerPwa();connectionState();hydrateLatest();render();load();
})();
